version: '3'

services:
  leader:
    build: .
    container_name: node1
    ports:
      - "50051:50051"
    environment:
      NODE_ID: "node1"
      IS_LEADER: "true"
      LEADER_ADDR: "node1:50051"
      PEERS: "node2:50051,node3:50051,,node4:50051"
    volumes:
      - ./data/node1:/app/data

  follower1:
    build: .
    container_name: node2
    ports:
      - "50052:50051"
    environment:
      NODE_ID: "node2"
      IS_LEADER: "false"
      LEADER_ADDR: "node1:50051"
      PEERS: "node1:50051,node3:50051,node4:50051"
    volumes:
      - ./data/node2:/app/data

  follower2:
    build: .
    container_name: node3
    ports:
      - "50053:50051"
    environment:
      NODE_ID: "node3"
      IS_LEADER: "false"
      LEADER_ADDR: "node1:50051"
      PEERS: "node1:50051,node2:50051,node4:50051"
    volumes:
      - ./data/node3:/app/data

  follower3:
    build: .
    container_name: node4
    ports:
      - "50054:50051"
    environment:
      NODE_ID: "node4"
      IS_LEADER: "false"
      LEADER_ADDR: "node1:50051"
      PEERS: "node1:50051,node2:50051,node3:50051"
    volumes:
      - ./data/node4:/app/data